/**
 * Данные уровней — темы, формы и параметры генерации
 */

const LEVELS = [
  {
    id: 1,
    name: 'Зал Входа',
    description: 'Первая камера древнего храма',
    width: 13,
    height: 11,
    shapes: ['rect', 'circle'],
    crystals: 1,
    traps: 0,
    deadEnds: 0,
    extraPassages: 2,
    minPathLen: 8,
    enemies: [],
    hasBoss: false,
    palette: {
      wallTop: '#9a8a6a', wallFront: '#6b5a3a', wallSide: '#4a3a2a', wallDark: '#3a2a1a',
      floor1: '#c4a35a', floor2: '#b8934a', floor3: '#a8833a',
      accent: '#ffd700', crystal: '#66ccff', trap: '#8a4444',
    },
  },
  {
    id: 2,
    name: 'Песчаные Катакомбы',
    description: 'Тёмные коридоры под храмом',
    width: 17,
    height: 15,
    shapes: ['rect', 'cross'],
    crystals: 2,
    traps: 1,
    deadEnds: 2,
    extraPassages: 6,
    minPathLen: 12,
    enemies: [{ type: 'patrol', count: 1 }],
    hasBoss: false,
    palette: {
      wallTop: '#8a7a5a', wallFront: '#5a4a2a', wallSide: '#3a2a1a', wallDark: '#2a1a0a',
      floor1: '#a8934a', floor2: '#98783a', floor3: '#88682a',
      accent: '#d4a84a', crystal: '#77bbee', trap: '#aa3333',
    },
  },
  {
    id: 3,
    name: 'Зал Кристаллов',
    description: 'Сверкающие кристаллы освещают путь',
    width: 21,
    height: 17,
    shapes: ['rect', 'octagon'],
    crystals: 3,
    traps: 2,
    deadEnds: 4,
    extraPassages: 14,
    minPathLen: 14,
    enemies: [
      { type: 'patrol', count: 1 },
      { type: 'chaser', count: 1 },
    ],
    hasBoss: false,
    palette: {
      wallTop: '#7a8a9a', wallFront: '#4a5a6a', wallSide: '#3a4a5a', wallDark: '#2a3a4a',
      floor1: '#9a8a7a', floor2: '#8a7a6a', floor3: '#7a6a5a',
      accent: '#aa88ff', crystal: '#44ddff', trap: '#cc4444',
    },
  },
  {
    id: 4,
    name: 'Огненные Залы',
    description: 'Раскалённые коридоры полны опасностей',
    width: 23,
    height: 19,
    shapes: ['rect', 'cross', 'circle'],
    crystals: 4,
    traps: 3,
    deadEnds: 5,
    extraPassages: 16,
    minPathLen: 16,
    enemies: [
      { type: 'patrol', count: 1 },
      { type: 'chaser', count: 1 },
      { type: 'sentry', count: 1 },
    ],
    hasBoss: false,
    palette: {
      wallTop: '#aa6a4a', wallFront: '#7a3a2a', wallSide: '#5a2a1a', wallDark: '#3a1a0a',
      floor1: '#ba7a4a', floor2: '#aa6a3a', floor3: '#9a5a2a',
      accent: '#ff6622', crystal: '#ffaa44', trap: '#ff2200',
    },
  },
  {
    id: 5,
    name: 'Внутреннее Святилище',
    description: 'Финальное испытание древних жрецов',
    width: 25,
    height: 21,
    shapes: ['rect', 'octagon', 'diamond'],
    crystals: 5,
    traps: 4,
    deadEnds: 6,
    extraPassages: 18,
    minPathLen: 18,
    enemies: [
      { type: 'patrol', count: 1 },
      { type: 'chaser', count: 1 },
      { type: 'sentry', count: 1 },
    ],
    hasBoss: true,
    palette: {
      wallTop: '#8a7a4a', wallFront: '#5a4a2a', wallSide: '#4a3a1a', wallDark: '#2a1a0a',
      floor1: '#b89a4a', floor2: '#a88a3a', floor3: '#987a2a',
      accent: '#ffdd44', crystal: '#eedd66', trap: '#dd2222',
    },
  },
];
